GET http://localhost:5000
###
GET http://localhost:5000/api/contact
Content-Type:  application/json
Authorization:  authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwNGFlMWZmNzBlMDVmMjk5NDcyOWU4NCIsIlVzZXJuYW1lIjoiZ2VkZ29ueiIsIlBhc3N3b3JkIjoiJDJiJDEwJE9QUFdGS2d5OThQU1FtY2NDR1BlV3U4Zi53OUd5bThCamkzRUtKalQxQngxUHlZSVJUbjhPIiwiY3JlYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIn0sImlhdCI6MTYxNTUyMTQzMCwiZXhwIjoxNjE1NjA3ODMwfQ.J9gj2tl1-nGBXL9YFYb8hoMVXNFBLri39nrADUqMp4s

###
GET http://localhost:5000/api/contact/1
Authorization:  authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwNGFlMWZmNzBlMDVmMjk5NDcyOWU4NCIsIlVzZXJuYW1lIjoiZ2VkZ29ueiIsIlBhc3N3b3JkIjoiJDJiJDEwJE9QUFdGS2d5OThQU1FtY2NDR1BlV3U4Zi53OUd5bThCamkzRUtKalQxQngxUHlZSVJUbjhPIiwiY3JlYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIn0sImlhdCI6MTYxNTUyMTQzMCwiZXhwIjoxNjE1NjA3ODMwfQ.J9gj2tl1-nGBXL9YFYb8hoMVXNFBLri39nrADUqMp4s

###
DELETE http://localhost:5000/api/contact/60419813de749432344b9c1d

### 
PUT  http://localhost:5000/api/contact/60406836726b592874c8743d
Content-Type:  application/json
Authorization:  authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwNGFlMWZmNzBlMDVmMjk5NDcyOWU4NCIsIlVzZXJuYW1lIjoiZ2VkZ29ueiIsIlBhc3N3b3JkIjoiJDJiJDEwJE9QUFdGS2d5OThQU1FtY2NDR1BlV3U4Zi53OUd5bThCamkzRUtKalQxQngxUHlZSVJUbjhPIiwiY3JlYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIn0sImlhdCI6MTYxNTUyMTQzMCwiZXhwIjoxNjE1NjA3ODMwfQ.J9gj2tl1-nGBXL9YFYb8hoMVXNFBLri39nrADUqMp4s

{
    "name": "Gerald",
    "lastname":"Gonzalez"
}
###
POST http://localhost:5000/api/contact
Content-Type: application/json
Authorization:  authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwNGFlMWZmNzBlMDVmMjk5NDcyOWU4NCIsIlVzZXJuYW1lIjoiZ2VkZ29ueiIsIlBhc3N3b3JkIjoiJDJiJDEwJE9QUFdGS2d5OThQU1FtY2NDR1BlV3U4Zi53OUd5bThCamkzRUtKalQxQngxUHlZSVJUbjhPIiwiY3JlYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIiwidXBkYXRlZEF0IjoiMjAyMS0wMy0xMlQwMzozNzozNS43NzVaIn0sImlhdCI6MTYxNTUyMTQzMCwiZXhwIjoxNjE1NjA3ODMwfQ.J9gj2tl1-nGBXL9YFYb8hoMVXNFBLri39nrADUqMp4s

{
    "name":"Pedro",
    "lastname": "Zeledon",
    "age": 50,
    "phonenumber": 57028365,
    "picture": "image3.png"
}
