GET http://localhost:3000
###
GET http://localhost:3000/api/contact
###
GET http://localhost:3000/api/contact/1
###
DELETE http://localhost:3000/api/contact/60419813de749432344b9c1d

### 
PUT  http://localhost:3000/api/contact/60406836726b592874c8743d
Content-Type:  application/json

{
    "name": "Jesus",
    "lastname":"Zeledon"
}
###
POST http://localhost:3000/api/contact
Content-Type: application/json

{
    "name":"Rosario",
    "lastname": "Zeledon",
    "age": 50,
    "phonenumber": 57028365,
    "picture": "image3.png"
}